### ISSUE TITLE
[EXT] Tela icon theme

### ISSUE THREAD

**Issue by Andevour** [Andevour/i3buntu#11]
# "Tela" icon pack - Outsourcing

## Description

The Tela icon pack, like the fonts too, need a proper outsourcing, as the folder is just too big. Like a CDN, maintainig the icon pack through `wget` is way simpler than uploading it in this repository. There is too much overhead, documentation wise and because of maintainability.

## Tasks

* [x] Work out a wrapper for getting and installing the icon pack
* [x] Integrate it into `packaging.sh`
* [x] Remove the sub-shell usage in `packaging.sh` for Tela

## Meta

The link location is <https://github.com/vinceliuice/Tela-icon-theme>. There is a dedicated branch for this issue, namely `extension/tela_icon_theme`.

## Related

**Comment by Andevour** [comment]
Done. [10.11.19-23:30]
