### ISSUE TITLE
[TES] Testing scripts

### ISSUE THREAD

**Issue by Andevour** [Andevour/i3buntu#13]
# Stability of scripts

## Description

The shell scripts are currently unstable and therefore in **beta** state. When Ubuntu 20.04 launches, the scripts will need to be tested and in case of major changes, reworked.

## Tasks

* [x] Test `packaging.sh`
* [x] Test `configuration.sh`
* [x] Test `fonts.sh`
* [x] Test `extensions.sh`
* [x] Test `icon_theme.sh`

## Related

**Comment by Andevour** [comment]
Done. [23.11.19-14:54]
