### ISSUE TITLE
[DES] i3lock new lockscreen

### ISSUE THREAD

**Issue by Andevour** [Andevour/i3buntu#19]
# i3lock lockscreen renewal

## Description

The latest lockscreen in use is `ì3lock-fancy`. There is a small change, where a new design is being introduced.

## Tasks

* [x] Remove now deprecated installation of i3lock-fancy
* [x] Create a PNG image out of _firewatch.jpg_
* [x] Setup new `bindsym` in i3 config file

## Meta

The corresponding command is `bindsym $mod+Shift+x exec i3lock -u -e -i ~/pictures/wallpapers/firewatch.png`

## Related

**Comment by Andevour** [comment]
Done. [20.11.19-19:33]
