### ISSUE TITLE
[WIKI] Features

### ISSUE THREAD

**Issue by Andevour** [Andevour/i3buntu#2]
# Features list

## Description

The list of features is currently non-existent. The wiki page needs to be filled.

## Tasks

* [x] Add core features
* [x] Add development features
* [x] Add nice-to-have features
* [x] Add an entry in `/README.md` to the wiki page for features

## Related

**Comment by Andevour** [comment]
Done. [20.11.19-20:47]
