### ISSUE TITLE
[CORE] Compton config

### ISSUE THREAD

**Issue by Andevour** [Andevour/i3buntu#26]
# Compton Configuration unset

## Description

Compton currently runs with command line options. There needs to be a config file, which sets up compton in a nicer way.

## Tasks

* [x] Setup config file
* [x]  In i3's config, start compton with different options
* [x] Add `compton-conf` to packaging

## Meta

The package is `compton-conf` is the graphical controller.

## Related

**Comment by Andevour** [comment]
Done. [21.11.19-21:40]
