### ISSUE TITLE
Migrate font folder to using scripts

### ISSUE THREAD

**Issue by Andevour** [Andevour/i3buntu#4]
# Better font integration

## Description

The font-management shall be de-centralized, i.e. the repository must not contain fully featured directories with fonts. They are a waste of solid state drive space.

## Tasks

* [x] Migrate FontAwesome
* [x] Migrate Iosevka
* [x] Migrate Open Sans
* [x] Migrate Roboto Mono Nerd
* [x] Migrate Roboto
* [x] Edit the scripts according to naming conventions and and integrate it into `configuration.sh` 

## Related

This issue is related to #1

**Comment by Andevour** [comment]
Done. [03.11.19-15:38]
