### ISSUE TITLE
[WIKI] Configuration of monitors with arandr

### ISSUE THREAD

**Issue by Andevour** [Andevour/i3buntu#5]
# Use of arandr at the end of configuration process

## Description

At the very end, after the `configuration.sh`-script has run, the user shall be prompted to setup his / her monitor with arandr, by executing the program, and saving the configuration in the i3 config.

## Tasks

* [x] Write a description in the wiki
* [x] Link a picture in the installation
* [x] edit `INSTALL.md` accordingly

## Related

**Comment by Andevour** [comment]
Done. [01.11.19-19:19]
