### ISSUE TITLE
[EXT] Install VS Code extensions during installation of packages

### ISSUE THREAD

**Issue by Andevour** [Andevour/i3buntu#7]
# Plug-In installation ad-hoc during packaging

## Description

The `packaging.sh`-script shall automatically install appropriate extensions and insert the `vs_code_settings_extra.json` file.

## Tasks

* [x] Make a list of appropriate extension
* [x] Add a script to `resources/sys/vscode/` to install all extensions
* [x] Let the user choose to install these extensions

## Meta

Is VS Code after installing it with snap already in `$PATH`?

## Related

**Comment by Andevour** [comment]
Done. [08.11.19-19:28]
