### ISSUE TITLE
[EXT] VS Code settings.json

### ISSUE THREAD

**Issue by Andevour** [Andevour/i3buntu#8]
# VS Code best `settings.json`

## Description

VS Code now has two distinct local settings files, which must be molded into one, single, comprehensive file.

## Tasks

* [x] Find _Markdown_ settings to obsolete two other markdown extensions (GitHub Preview)
* [x] Mold two files into one
* [x] insert this file during installation

## Meta

The markdown GitHub preview may not be available through one extension only. But a lookup would be nice here. Maybe, one of the 3 markdown extensions (excluding the linter) can be removed.

## Related

**Comment by Andevour** [comment]
Done. [08.11.19-19:28]
