### ISSUE TITLE
[EXT] Revise font integration

### ISSUE THREAD

**Issue by Andevour** [Andevour/i3buntu#9]
# Font integration revisited

## Description

The integration of installing fonts has been done, but could be rewritten in some places. Mainly getting large chunks of code out of `configuration.sh` and into a wrapper script.

## Tasks

* [x] Outsource installation of fonts
* [x] create wrapper script to outsource to
* [x] Coherent structure in comparison to the rest of the script

## Related

This issue is related to #4

**Comment by Andevour** [comment]
Done. [08.11.19-19:33]

**Comment by Andevour** [comment]
Done. [08.11.19-19:33]
